version: '3'

volumes:
  gems:
  mysql:

services:
  app:
    build: .
    command: bundle exec rails s -b 0.0.0.0
    tty: true
    stdin_open: true
    volumes:
      - .:/usr/src/app:cached
      - gems:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'example'
      MYSQL_ROOT_HOST: '%'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db